services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./gourmet_search:/gourmet_search
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    command: python manage.py runserver 0.0.0.0:8000
